(function(g){var window=this;var Z4=function(a){var b={format:a.A,languageCode:a.o,languageName:a.D,displayName:g.wH(a),kind:a.B,name:a.C,id:a.Ca,is_servable:a.N,is_translateable:a.G,vss_id:a.F};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},$4=function(a){return a.g?a.g.languageCode:a.o},hwa=function(a,b){var c=new g.vH;
c.o=a.o;c.D=a.D;c.C=a.C;c.B=a.B;c.G=a.G;c.F=a.F;c.I=a.I;c.g=b;return c},iwa=function(a){a=g.ld(window.document,"track",void 0,a.g);
for(var b=0;b<a.length;b++)g.Ed(a[b])},jwa=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},a5=function(a){if(!kwa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(lwa,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},b5=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.gP.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.C=f;this.o=k},c5=function(a,b,c,d,e){g.gP.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},e5=function(a){a=void 0===a?{}:a;
var b="_"+d5++;return new c5(0,0x8000000000000,0,b,a)},f5=function(a,b,c,d,e,f){var k={};
g.Ea(k,b);g.Ea(k,a.params);g.Ea(k,c);var l={};g.Ea(l,b.sb);a.params.sb&&g.Ea(l,a.params.sb);g.Ea(l,c.sb);k.sb=l;g.X.call(this,{H:"div",M:"caption-window",U:{id:"caption-window-"+a.id,dir:1==k.bk?"rtl":"ltr",tabindex:0,"aria-live":"assertive",lang:k.lang},K:[{H:"span",M:"captions-text"}]});this.A=[];this.J=!1;this.F=a;this.D=[];this.G=[];this.va=e;this.pa=f;this.C=null;this.W=.96*e;this.ea=.96*f;this.o=k;this.na=c;this.B=this.sa["captions-text"];this.ga=null!=this.B.style["box-decoration-break"]||
null!=this.B.style["-webkit-box-decoration-break"];this.L=d/360*16;this.type=0;this.Z=this.L*mwa(l);a=new g.nF(this.element,!0);g.N(this,a);a.subscribe("dragstart",this.nL,this);a.subscribe("dragmove",this.mL,this);a.subscribe("dragend",this.lL,this);this.da=this.ca=0;a="";this.o.nk&&(a=a5(this.o.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.o.nk+")");b={"background-color":a,display:!1===this.o.isVisible?"none":"","text-align":nwa[this.o.textAlign]};this.ga&&(b["border-radius"]=a?this.Z/
8+"px":"");g.lh(this.element,b);switch(this.o.Tg){case 0:case 1:case 2:g.S(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.S(this.element,"ytp-caption-window-bottom")}},mwa=function(a){var b=1+.25*(a.cj||0);
if(0==a.offset||2==a.offset)b*=.8;return b},g5=function(a,b){var c={},d=b.background?b.background:a.o.sb.background;
if(null!=b.Ye||b.background){var e=null!=b.Ye?b.Ye:a.o.sb.Ye;d=a5(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.ga&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Z/8+"px")}if(null!=b.cj||null!=b.offset)c["font-size"]=a.L*mwa(b)+"px";d=1;e=b.color||a.o.sb.color;if(b.color||null!=b.Gh)e=a5(e),d=null==b.Gh?a.o.sb.Gh:b.Gh,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;var f=b.Th;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.iw&&
(k=e=b.iw);var l=a.L/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';
break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.bE()?'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e=
'"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.o.sb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Xr&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");b.qr&&(c.visibility="hidden");return c},owa=function(a,b,c){a.J=a.J||!!c;
var d={};g.Ea(d,a.o.sb);g.Ea(d,c||b.o);g.Ea(d,a.na.sb);c=a.D[0];if(c&&d.background==c.background&&d.Ye==c.Ye&&!!d.qr==!!c.qr&&d.Th==c.Th){var e;for(e=0;e<a.D.length;e++)if(jwa(d,a.D[e])){var f=a.G[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.yd("SPAN");g.lh(f,g5(a,e));a.G[0].appendChild(f);e=1}a.G.length=e;a.D.length=e}else a.G.length=0,a.D.length=0,f=g.yd("SPAN"),g.lh(f,g5(a,d)),a.B.appendChild(f);a.C&&a.C.parentNode!=f&&(g.Ed(a.C),f.appendChild(a.C));c=(k=g.u(b.text))?b.text.split("\n"):
[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.A.length||!b.C){if(0<e||0!=a.A.length){var m=g.yd("BR");f.appendChild(m)}f.appendChild(g.zd("\u00a0"));a.C=g.zd("\u00a0");f.appendChild(a.C)}l&&(m=a.C,m.parentNode&&m.parentNode.insertBefore(k?g.zd(l):l,m))}a.D.push(d);a.G.push(f);a.A.push(b)},pwa=function(){},i5=function(){this.B=this.o=this.mode=this.A=0;
this.C=new h5(this);this.D=new h5(this);this.g=[];this.clear()},rwa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Hm:a,
Im:b,result:0};a=qwa[a];b=qwa[b];if(a&128){if(!(b&128)&&0!=c.g&&c.o==b)return{Hm:a,Im:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Hm:a,Im:b,result:2};return{Hm:a,Im:b,result:3}},twa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.B&&a.reset(),a.C.g.clear(),a.D.g.clear()):(a.B=0,swa(a.C,b,c,d))},uwa=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.o=d.time;0==d.type?twa(a,d.cw,d.dw,b):1==d.type&&a.A&496&&swa(a.D,d.cw,d.dw,b)}a.g.length=0},j5=function(){this.g=0},k5=function(){this.o=this.A=this.g=0},l5=function(){this.timestamp=this.pe=0;
this.g=!1},m5=function(a){this.A=[];
for(var b=0;15>=b;b++){this.A[b]=[];for(var c=0;32>=c;c++)this.A[b][c]=new l5}this.g=this.o=this.Ec=0;this.style=new j5;this.C=a;this.B=0},n5=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.C.o+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.A[m][q];
if(0!=r.pe){0==c&&(c=m,d=q);n=String.fromCharCode(r.pe);var v=r.timestamp;v<e&&(e=v);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.pe||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.C.o+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.A[k][m],r=q.pe,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),v=q.timestamp,v<=e&&(e=v),l+=n,q.reset()),32==m||0==r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},zwa=function(a,b){switch(a){case 0:return vwa[(b&127)-32];
case 1:return wwa[b&15];case 2:return xwa[b&31];case 3:return ywa[b&31]}return 0},o5=function(a){return a.A[a.Ec][a.o]},p5=function(a,b,c){2<=b&&1<a.o&&(--a.o,o5(a).pe=0);
var d=o5(a);d.timestamp=a.C.o+0;d.pe=zwa(b,c);32>a.o&&a.o++},Awa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.A[b+e][f].an(a.A[c+e][f])},q5=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},r5=function(a){a.Ec=0<a.g?a.g:1;
a.o=1;q5(a,0,15)},s5=function(a){this.B=a;
this.C=0;this.style=new j5;this.D=new m5(a);this.F=new m5(a);this.G=new m5(a);this.o=this.D;this.A=this.F;this.g=this.o},t5=function(a,b,c){var d=a.o,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:n5(d,c),r5(a.o),r5(a.A),d.Ec=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.B.mode=1<<d.B;e?d.o=1:d.g!=b&&(d.g>b?(n5(d,c),q5(d,d.Ec-d.g,b)):d.Ec<b&&(b=d.g),d.g=b)},Bwa=function(a){a.style.set(1);
a.g=a.A;a.g.g=0;a.g.style=a.style;a.B.mode=1<<a.g.B},Cwa=function(a){a.style.set(4);
a.g=a.G;a.g.style=a.style;a.B.mode=1<<a.g.B},h5=function(a){this.o=a;
this.g=new k5;this.C=0;this.A=new s5(a);this.D=new s5(a);this.B=this.A},swa=function(a,b,c,d){a.g.update();
b=rwa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Hm;c=b.Im;if(32<=e||!e)a.o.mode&a.o.A&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.B.g,b&96&&p5(a,0,b),c&96&&p5(a,0,c),0!=b&&0!=c&&3==a.style.g&&n5(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.A=e,b.o=c,b.g=2,b=e&8?a.D:a.A,a.B=b,a.o.mode=1<<(a.C<<2)+(b.C<<1)+(4==b.style.g?1:0),(a.o.mode|1<<(a.C<<2)+(b.C<<1)+(4!=b.style.g?1:0))&a.o.A))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.Ec;break;case 3:if(d!=c.Ec){if(d<c.g&&(d=c.g,d==c.Ec))break;var f=1+c.Ec-c.g,k=1+d-c.g;Awa(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));q5(c,b,e)}}c.Ec=d;c.o=a+1}else switch(e&7){case 1:switch(c&112){case 32:p5(b.g,0,32);break a;case 48:57==c?(b=b.g,o5(b).pe=0,32>b.o&&b.o++):p5(b.g,1,c&15)}break;case 2:c&32&&p5(b.g,2,c&31);break;case 3:c&32&&p5(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Bwa(b);break;case 33:b=
b.g;1<b.o&&(--b.o,o5(b).pe=0);break;case 36:b=b.g;d=o5(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.A[a][c]==d){for(;32>=c;c++)b.A[a][c].reset();break}break;case 37:t5(b,2,d);break;case 38:t5(b,3,d);break;case 39:t5(b,4,d);break;case 40:p5(b.g,0,32);break;case 41:b.style.set(2);b.g=b.o;b.g.g=0;b.g.style=b.style;b.B.mode=1<<b.g.B;break;case 42:d=b.G;d.g=15;d.style.set(4);r5(d);Cwa(b);break;case 43:Cwa(b);break;case 44:a=b.o;switch(b.style.get()){case 1:case 2:case 3:n5(a,d)}q5(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.Ec){++a.Ec;a.o=1;break b}case 3:}2>a.g&&(a.g=2,a.Ec<a.g&&(a.Ec=a.g));b=a.Ec-a.g+1;n5(a,d);Awa(a,b,b+1,a.g-1);q5(a,a.Ec,1)}break;case 46:q5(b.A,0,15);break;case 47:n5(b.o,d);d=b.A;a=b.B.o+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.A[c][e].timestamp=a;d=b.A;b.A=b.o;b.o=d;Bwa(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.o+=c&3)&&(b.o=32)}}},u5=function(){},v5=function(a){this.A=a;
this.o=null},Ewa=function(a,b,c){var d=a.getAttribute("t");
d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0);var e=a.getAttribute("d");e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.Mr("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");Dwa(d,e,k,b,f,a.firstChild,{},c)},Dwa=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.Xr=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");w5.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new b5(a,b,c,d,n.nodeValue,e||0<m,g.Wb(k)?void 0:k));else{var q={};g.Ea(q,k);Dwa(a,b,c,d,e||0<m,n,q,l)}}},x5=function(){this.A={};
this.o=null},y5=function(a){this.o={};
this.C={};this.D={};this.A="_"+d5++;this.B=a},z5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},A5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},B5=function(a,b){var c=z5(a,b);
if(void 0!=c)return c},C5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return w5.test(c),c},Fwa=function(a,b){var c={},d=b.getAttribute("ws");
g.Ea(c,d?a.D[d]:a.B);d=B5(b,"mh");null!=d&&(c.ts=d);d=B5(b,"ju");null!=d&&(c.textAlign=d);d=B5(b,"pd");null!=d&&(c.bk=d);d=C5(b,"wfc");null!=d&&(c.windowColor=d);d=z5(b,"wfo");void 0!=d&&(c.nk=d/255);return c},Gwa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ea(c,a.C[d]);d=B5(b,"ap");null!=d&&(c.Tg=d);d=z5(b,"cc");null!=d&&(c.WG=d);d=z5(b,"ah");null!=d&&(c.pi=d);d=z5(b,"rc");null!=d&&(c.Qo=d);d=z5(b,"av");null!=d&&(c.Mi=d);return c},Hwa=function(a,b,c){var d={};
g.Ea(d,Gwa(a,b));g.Ea(d,Fwa(a,b));c?jwa(d,a.B)?(c=a.A,d=a.B):c="_"+d5++:c=b.getAttribute("id")||"0";a=z5(b,"t");b=z5(b,"d")||0x8000000000000;return new c5(a,b,0,c,d)},D5=function(a,b,c){this.F=c;
this.version=this.C=this.D=this.g=0;this.o=new window.DataView(a);this.A=[]},E5=function(a){var b=a.g;
a.g+=1;return a.o.getUint8(b)},Iwa=function(a){var b=a.g;
a.g+=4;return a.o.getUint32(b)},F5=function(a,b){this.A=a;
this.track="CC3"==b.D?4:0;this.o=new i5;this.o.A=1<<this.track},Jwa=function(a){if(!(a.g<a.o.byteLength))return!1;
var b=Iwa(a);b.toString(16);if(1380139777!=b)return!1;a.version=E5(a);if(1<a.version)return!1;E5(a);E5(a);E5(a);return!0},Kwa=function(){this.o=[];
this.g=[]},G5=function(a,b){return b?a.g.concat(a.o):a.g},H5=function(a,b){switch(b.B){case "asr":var c=a.o;
g.Ja(c,(0,g.z)(b.J,b))||c.push(b);break;default:c=a.g,g.Ja(c,(0,g.z)(b.J,b))||c.push(b)}},I5=function(){this.o=null},Lwa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Xr=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new b5(b,c,d,e.id,q.nodeValue,f||0<n,g.Wb(l)?void 0:l),m.push(q),e!=a.o&&e.o.push(q);else{var r={};g.Ea(r,l);Lwa(a,b,c,d,e,!0,q,r,m)}}},J5=function(a){var b=0;
a=g.la(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+c.value;return 1E3*b},K5=function(a){g.M.call(this);
this.uy=!!a;this.o=new Kwa;this.F=[];this.g=null},Nwa=function(a){var b={};
if(a=$4(a))b.lang=a,Mwa.test(a)&&(b.bk=1);return b},Owa=function(a,b,c,d,e){d=d||0;
e=e||0;if(g.u(b)){if("WEBVTT"==b.substring(0,6))return a.g||(a.g=new I5),a.g.g(b,d);b=g.Mr(b);if(!b||!b.firstChild)return[];a.g||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.g=new y5(Nwa(c)):a.g=new x5:a.g=new v5(Nwa(c)));return a.g.g(b,d)}try{if(g.u(b))var f=!1;else{var k=new D5(b,8,0);f=Jwa(k)}if(f)return a.g||(a.g=new F5(e,c)),a.g.g(b,d)}catch(l){g.yD(l)}return[]},L5=function(a){K5.call(this,a.Om);
this.B=void 0;this.A=null;this.F=a.captionTranslationLanguages},M5=function(){this.tb=[]},N5=function(a,b,c,d,e,f){g.M.call(this);
this.D=b;this.B=new M5;this.g=null;this.F=d;this.J=f;this.o=this.A=null;this.L=c;this.C=e||!1;this.G=new g.Nt(this.Iy,1E3,this);g.N(this,this.G);this.I=new g.iF(this);g.N(this,this.I);this.I.P(b,"seekto",this.vz);this.vz(b.getCurrentTime());this.Iy()},Pwa=function(a,b){var c=g.vJ(b,{}).Pa(),d={format:"RAW",
fd:(0,g.z)(a.WQ,a),withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.o=g.TD(c,d);a.A=b;c=a.B;d=a.A.za[0].ra;var e=g.db(c.tb,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.tb[e-1]&&e<c.tb.length&&1==c.tb[e]-d?(g.Sa(c.tb,e),g.Sa(c.tb,e-1)):0<e&&1==d-c.tb[e-1]?c.tb[e-1]=d:e<c.tb.length&&1==c.tb[e]-d?c.tb[e]=d:(g.Za(c.tb,e,0,d),g.Za(c.tb,e+1,0,d)))},O5=function(a,b){K5.call(this);
this.B=a;this.C=b;this.A=null;this.D=!1},Qwa=function(a,b){if(b in a.B.g)return a.B.g[b];
if(g.UJ(a.B))for(var c in a.B.g){var d=a.B.g[c];if(d.info.mimeType.includes("vtt"))return d}return null},P5=function(a,b,c,d,e,f){f5.call(this,a,b,c,d,e,f);
this.type=1},Q5=function(a,b,c,d,e,f){f5.call(this,a,b,c,d,e,f);
g.S(this.element,"ytp-caption-window-rollup");this.type=2;this.I=this.N=0;this.O=window.NaN;this.la=null;this.X=new g.Nt(this.aR,433,this);g.N(this,this.X)},R5=function(a){if(!a.N){var b=g.yd("SPAN");
g.lh(b,g5(a,a.o.sb));a.B.appendChild(b);b.appendChild(g.zd("M"));var c=b.offsetHeight,d=g.yd("BR");b.appendChild(d);b.appendChild(g.zd("M"));a.N=b.offsetHeight-c;a.B.removeChild(b)}return a.N},S5=function(a,b,c,d){K5.call(this,d);
c=c||g.KD(a).hl||"";c=c.split("_").join("-");this.C=g.MD(a,{hl:c});this.B=b;this.D={};this.A=null},V5=function(a){g.uU.call(this,a);
g.sG({YTP_CLICK_FOR_SETTINGS:"Click $GEAR_ICON for settings",YTP_SAMPLE_SUBTITLES:"Captions look like this"});this.A=g.W(a);this.B=a.fa();this.la=g.UT(a);this.L=a;var b=null,c=g.VC("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.JC(c));this.ca=b;this.D={sb:{}};this.I={sb:{}};this.N=[];this.W={};this.Z={};this.O=!1;this.na="1"==this.B.Xb.cc_auto_caps||"1"==this.A.Xa.cc_auto_caps;this.G="3"==this.A.A&&!!a.app.C&&!!a.app.C.g.textTracks;c=b=this.o=this.C=this.F=this.J=this.aa=this.ga=null;
this.G||(b=new g.Kt(this.YC,void 0,this),g.N(this,b),c=new g.Nt(this.NS,2E3,this),g.N(this,c));this.da=b;this.ea=c;this.X=new g.iF(this);g.N(this,this.X);this.G||this.X.P(a,"resize",this.nu);this.X.P(a,"onPlaybackAudioChange",this.bO);this.X.P(a,"crn_captions",this.QK,this);this.X.P(a,"crx_captions",this.RK,this);T5(this,U5(this,"display-settings")||{})},Rwa=function(a){if(a.B.captionTracks.length)var b=a.g.wh().Zv;
if("FORCED_ON"==b||1==a.A.Xg||1==a.B.Xg||"alwayson"==g.uN(a.B,"yt:cc"))return!0;if(2==a.A.Xg){var c=U5(a,"module-enabled");if(null!=c)return!!c}return"ON"==b||"on"==g.uN(a.B,"yt:cc")},Swa=function(a,b){if(a.C){var c=G5(a.C.o,b||a.na);
if(a.F&&a.F.g)return a.F.g;for(var d=[a.B.Wg,a.A.Wg,g.uN(a.B,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if($4(c[f])==d[e])return c[f];return a.F&&a.F.zq?a.F.zq:c[0]||a.F&&a.F.Fk}return null},Twa=function(a,b){for(var c=a.L.app.C.g.textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},W5=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.O=c);a.o=b;a.load(d)},Uwa=function(a,b){var c=g.MY(a.la,!0).height;
if(!c)return null;var d=a.la.Va();switch(null!=b.params.ts?b.params.ts:b.params.BT?2:1<b.o.length?1:0){case 1:return new P5(b,a.D,a.I,c,d.width,d.height);case 2:return new Q5(b,a.D,a.I,c,d.width,d.height);default:return new f5(b,a.D,a.I,c,d.width,d.height)}},T5=function(a,b,c){var d=X5.sb;
a.D={};g.Ea(a.D,X5);a.D.sb={};g.Ea(a.D.sb,d);a.I={sb:{}};var e=b.backgroundOverride?a.I:a.D,f=b.background||d.background;w5.test(f);e.sb.background=f;e=b.colorOverride?a.I:a.D;f=b.color||d.color;w5.test(f);e.sb.color=f;e=b.windowColorOverride?a.I:a.D;f=b.windowColor||X5.windowColor;w5.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.I:a.D;f=b.backgroundOpacity;null==f&&(f=d.Ye);e.sb.Ye=f;e=b.fontSizeIncrementOverride?a.I:a.D;f=b.fontSizeIncrement;null==f&&(f=d.cj);e.sb.cj=f;e=b.textOpacityOverride?
a.I:a.D;f=b.textOpacity;null==f&&(f=d.Gh);e.sb.Gh=f;e=b.windowOpacityOverride?a.I:a.D;f=b.windowOpacity;null==f&&(f=X5.nk);e.nk=f;e=b.charEdgeStyleOverride?a.I:a.D;f=b.charEdgeStyle;null==f&&(f=d.Th);e.sb.Th=f;e=b.fontFamilyOverride?a.I:a.D;f=b.fontFamily;null==f&&(f=d.fontFamily);e.sb.fontFamily=f;a.loaded&&a.nu();c&&Y5(a,"display-settings",b)},Wwa=function(a,b){if(b&&!a.J){var c=e5({bk:0,
lang:"en"});a.J=[c,new b5(c.start,c.end-c.start,0,c.id,g.U("YTP_SAMPLE_SUBTITLES"))];g.hU(a.g,a.J)}else!b&&a.J&&(Vwa(a,a.J),a.J=null)},Vwa=function(a,b){g.jU(a.g,b);
(0,g.C)(b,function(a){g.Ta(this.N,a)},a);
a.da.Nk()},Xwa=function(a,b){return a&&g.u(a)&&w5.test(a)?a:b},Ywa=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},$wa=function(a,b){if(a&&g.u(a)){var c=Zwa.indexOf(a);
return-1!=c?c:b}return b},bxa=function(a,b){if(a&&g.u(a)){var c=axa.indexOf(a);
return-1!=c?c:b}return b},cxa=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?g.Yc(a,-2,4):b},U5=function(a,b){if(!a.ca)return null;
try{var c=a.ca.get(b)}catch(d){a.ca.remove(b)}return c},Y5=function(a,b,c){if(a.ca)try{a.ca.set(b,c)}catch(d){}};
g.BH.prototype.Dn=g.ca(4,function(a){return(a=this.Yh(a))?a.o:0});
g.KJ.prototype.Dn=g.ca(3,function(){return 0});
g.vH.prototype.J=g.ca(2,function(a){return a?this.toString()==a.toString():!1});
var Mwa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,lwa=/#(.)(.)(.)/,kwa=/^#(?:[0-9a-f]{3}){1,2}$/i,w5=/^#(?:[0-9a-f]{3}){1,2}$/i,axa="default monoSerif propSerif monoSans propSans casual cursive smallCaps".split(" "),Zwa=["none","raised","depressed","uniform","dropShadow"];var nwa=["left","right","center"];var X5={windowColor:"#080808",nk:0,textAlign:2,Tg:7,pi:50,Mi:100,sb:{background:"#080808",Ye:.75,Th:0,color:"#fff",fontFamily:4,cj:0,Gh:1,offset:1}};g.p(b5,g.gP);g.p(c5,g.gP);var d5=0;g.p(f5,g.X);g.h=f5.prototype;g.h.nL=function(a,b){var c=g.Bh(this.element,this.element.parentElement);this.ca=a-c.x;this.da=b-c.y;g.S(this.element,"ytp-dragging")};
g.h.mL=function(a,b){var c=g.Eh(this.element),d=a-this.ca-.02*this.va,e=b-this.da-.02*this.pa,f=(d+c.width/2)/this.W*3;f=Math.floor(g.Yc(f,0,2));var k=(e+c.height/2)/this.ea*3;k=Math.floor(g.Yc(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.W;d=100*g.Yc(d,0,1);c=(e+k/2*c.height)/this.ea;c=100*g.Yc(c,0,1);this.F.params.Tg=l;this.F.params.Mi=c;this.F.params.pi=d;this.o.Tg=l;this.o.Mi=c;this.o.pi=d;this.UB()};
g.h.lL=function(){g.hq(this.element,"ytp-dragging")};
g.h.UB=function(){this.Ji(this.A)};
g.h.Tb=function(){return this.type};
g.h.Ji=function(a){var b=Math.min(this.mx(),this.W),c=this.lx();g.lh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Xp(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var d=.96*this.o.pi+2,e=this.o.Tg;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.B.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=
b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-d+"%"}b=.96*this.o.Mi+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.lh(this.element,a)};
g.h.Xp=function(a){var b;for(b=0;b<a.length&&a[b]==this.A[b];b++);if(this.J||this.A.length>b)b=0,this.J=!1,this.A=[],this.D=[],this.G=[],this.C=null,g.Cd(this.B);for(;b<a.length;b++)owa(this,a[b])};
g.h.mx=function(){return 0};
g.h.lx=function(){return 0};
g.h.toString=function(){return g.X.prototype.toString.call(this)};pwa.prototype.B=function(){};i5.prototype.clear=function(){this.B=this.o=this.mode=0;this.g=[];this.reset()};
i5.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var qwa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];j5.prototype.set=function(a){this.g=a};
j5.prototype.get=function(){return this.g};
k5.prototype.clear=function(){this.g=0};
k5.prototype.update=function(){this.g=2==this.g?1:0};
k5.prototype.matches=function(a,b){return 0!=this.g&&a==this.A&&b==this.o};
l5.prototype.an=function(a){this.pe=a.pe;this.timestamp=a.timestamp;this.g=a.g};
l5.prototype.reset=function(){this.timestamp=this.pe=0;this.g=!1};
m5.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.A[b][c];a=0==d.pe?a+"_":a+String.fromCharCode(d.pe)}a+="\n"}return a};
m5.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.B=a;this.g=0;this.o=this.Ec=1};
var vwa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],wwa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],xwa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],ywa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];s5.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.o=this.D;this.A=this.F;this.g=this.o;var c=(a<<2)+(b<<1)+0;this.D.reset(c);this.F.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
h5.prototype.reset=function(a){this.C=a;this.g.clear();this.B=this.A;this.A.reset(a,0);this.D.reset(a,1)};u5.prototype.reset=function(){};g.p(v5,u5);v5.prototype.g=function(a){var b=[];this.o||(this.o=e5(this.A),b.push(this.o));a=g.la(a.firstChild.childNodes);for(var c=a.next();!c.done;c=a.next())Ewa(c.value,this.o.id,b);return b};g.p(x5,u5);
x5.prototype.g=function(a){var b=[];this.o||(this.o=e5(),this.A[this.o.id]=this.o,b.push(this.o));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.A[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=e5());
var k={};f&&(g.Ea(k,f.params),f=f.params.sb)&&(k.sb={},g.Ea(k.sb,f));e.getAttribute("rc")&&(k.Qo=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.WG=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.Tg=0>f||8<f?7:f);e.getAttribute("ah")&&(k.pi=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.Mi=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.bk=1,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.bk=0));e.getAttribute("bc")&&(k.sb||(k.sb={}),k.sb.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.sb||(k.sb={}),k.sb.Ye=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.sb||(k.sb={}),k.sb.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.BT=(0,window.parseInt)(e.getAttribute("sd"),10));f=(0,window.parseInt)(e.getAttribute("d"),
10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"0";c=new c5(c,f,0,e,k)}else c=null}this.A[d]=c;b.push(c);break;case "text":for(d=[],Ewa(a,this.o.id,d),d=g.la(d),c=d.next();!c.done;c=d.next())c=c.value,this.A[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.p(y5,u5);
y5.prototype.g=function(a){a.firstChild.getAttribute("format");a=g.la(a.firstChild.childNodes);for(var b=a.next();!b.done;b=a.next())switch(b=b.value,b.tagName){case "head":var c=b;break;case "body":var d=b}if(c)for(c=g.la(c.childNodes),a=c.next();!a.done;a=c.next())switch(a=a.value,a.tagName){case "pen":b=a.getAttribute("id");var e=this.o,f={},k=a.getAttribute("p");k&&g.Ea(f,this.o[k]);k=A5(a,"b");null!=k&&(f.bold=k);k=A5(a,"i");null!=k&&(f.Xr=k);k=A5(a,"u");null!=k&&(f.underline=k);k=B5(a,"et");
null!=k&&(f.Th=k);k=B5(a,"of");null!=k&&(f.offset=k);k=C5(a,"bc");null!=k&&(f.background=k);k=C5(a,"ec");null!=k&&(f.iw=k);k=C5(a,"fc");null!=k&&(f.color=k);k=B5(a,"fs");void 0!=k&&0!=k&&(f.fontFamily=k);k=z5(a,"sz");void 0!=k&&(f.cj=k/100-1);k=z5(a,"bo");void 0!=k&&(f.Ye=k/255);a=z5(a,"fo");void 0!=a&&(f.Gh=a/255);e[b]=f;break;case "ws":b=a.getAttribute("id");this.D[b]=Fwa(this,a);break;case "wp":b=a.getAttribute("id"),this.C[b]=Gwa(this,a)}c=[];if(d)for(a={},b=void 0,d=g.la(d.childNodes),e=d.next();!e.done;e=
d.next())switch(e=e.value,e.tagName){case "w":var l=Hwa(this,e,!1);(e=a[l.id])&&e.end>l.start&&(e.end=l.start);a[l.id]=l;c.push(l);break;case "p":var m=b,n=te;f=[];k=e.getAttribute("w")||this.A;var q=!!A5(e,"a"),r=z5(e,"t")||0,v=z5(e,"d")||5E3;!n&&!q&&m&&m.windowId==k&&m.end>r&&(m.end=r);m=q?6:5;n=this.o[e.getAttribute("p")];for(var B=e.childNodes,F=0;F<B.length;F++){var I=B[F];0<F&&(q=!0);if("s"==I.tagName){var Y=I;I=r;var na=v,ab=k,La=q,Na=m,mi=Y.textContent?Y.textContent:"",zb=this.o[Y.getAttribute("p")];
Y=z5(Y,"t")||0;I=new b5(I+Y,na-Y,Na,ab,mi,La,zb)}else I=new b5(r,v,m,k,I.textContent||"",q,n);f.push(I)}b&&"\n"==b.text&&(b.text="");if(0<f.length){b=f[f.length-1];var te=null!=e.getAttribute("d");f[0].windowId==this.A&&(l=Hwa(this,e,!0),c.push(l));e=g.la(f);for(f=e.next();!f.done;f=e.next())f=f.value,f.windowId=l.id,l.o.push(f),c.push(f)}}return c};g.p(D5,pwa);D5.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+d5++;c=c/1E3-this.F;d=d/1E3-this.F;a=new c5(c,d-c,5,f,{textAlign:0,Tg:0,pi:2.5*b,Mi:5.33*a});e=new b5(c,d-c,5,f,e);this.A.push(a);this.A.push(e)}};
g.p(F5,u5);F5.prototype.g=function(a){a=new D5(a,a.byteLength,this.A);if(Jwa(a)){for(;a.g<a.o.byteLength;)for(0==a.version&&(a.D=Iwa(a)*(1E3/45)),a.C=E5(a);0<a.C;a.C--){var b=E5(a),c=E5(a),d=E5(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.o,b.g.push({time:a.D,type:this.track,cw:c,dw:d,order:b.g.length}))}uwa(this.o,a);return a.A}return[]};
F5.prototype.reset=function(){this.o.clear()};g.p(I5,u5);
I5.prototype.g=function(a,b){for(var c=[],d=a.split(dxa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!exa.test(f)){var l=Z5.exec(f);if(l&&3<=l.length){var m=J5(l[1]);l=J5(l[2])-m;m+=k;f=f.substring(Z5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");Z5.lastIndex=0;var n=f;f={};this.o||(this.o=e5({ts:0}),c.push(this.o));var q=this.o;k=5;if(0>n.indexOf("<")&&0>n.indexOf("&"))c.push(new b5(m,l,k,q.id,n,!1,g.Wb(f)?void 0:f));else{n=n.split(fxa);1!=n.length&&(k=6,q="_"+gxa++,q=new c5(m,l,k,q,{}),c.push(q));
for(var r=m,v=0;v<n.length;v++){var B=n[v];if(0==v%2){var F=g.Mr("<html>"+B+"</html>");if(F.getElementsByTagName("parsererror").length){var I=F.createElement("span");I.appendChild(F.createTextNode(B))}else I=F.firstChild;Lwa(this,r,l-(r-m),k,q,0<v,I,f,c)}else r=J5(B)}}}Z5.lastIndex=0}}return c};
var gxa=0,exa=/^NOTE/,dxa=/(?:\r\n|\r|\n){2,}/,Z5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3}).*(?:\r\n|\r|\n)","gm"),fxa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.p(K5,g.M);K5.prototype.trackCount=function(){return G5(this.o,!0).length};
K5.prototype.Fd=function(){this.g=null};
K5.prototype.V=function(){g.M.prototype.V.call(this);this.Fd()};
K5.prototype.GB=function(){return!1};g.p(L5,K5);g.h=L5.prototype;g.h.ks=function(a,b){var c=this.Lk(a),d=(0,g.z)(function(c){this.A=null;b(c.responseText,a)},this);
this.Fd();this.A=g.TD(c,{format:"RAW",Jb:d,withCredentials:!0})};
g.h.ls=function(a,b,c,d){this.B=c;if(d)for(b=g.la(d.captionTracks),c=b.next();!c.done;c=b.next())H5(this.o,c.value);a()};
g.h.Lk=function(a){var b=a.Pa(),c={};if(this.B||a.A)c.fmt=this.B||"srv"+a.A;a.g&&(c.tlang=a.g.languageCode);return g.MD(b,c)};
g.h.Fd=function(){K5.prototype.Fd.call(this);this.A&&this.A.abort()};
g.h.V=function(){this.Fd();K5.prototype.V.call(this)};M5.prototype.contains=function(a){a=g.db(this.tb,a);return 0<=a||0>a&&1==(-a-1)%2};
M5.prototype.length=function(){return this.tb.length/2};g.p(N5,g.M);g.h=N5.prototype;g.h.V=function(){g.M.prototype.V.call(this);this.o&&this.o.abort()};
g.h.vz=function(a){var b=this.g;this.g=g.Ha(this.L.gh(a).za);b!=this.g&&this.J&&this.J()};
g.h.reset=function(){this.B=new M5;this.o&&(this.o.abort(),this.o=null)};
g.h.Iy=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.wi(a);!a||this.o||this.g&&30<this.g.startTime-this.D.getCurrentTime()||(a=this.g,a=a.g.il(a),!g.W(this.D).experiments.g("disable_captions_unknown_requests")&&!a.za[0].duration)||(this.B.contains(a.za[0].ra)||Pwa(this,a),this.g=g.Ha(a.za));this.G.start()};
g.h.WQ=function(a){var b=!(this.C?a.response:a.responseText)||400<=a.status;if(!g.W(this.D).experiments.g("disable_captions_redirects_redux")){var c=g.PJ(a);if(c){a=g.vJ(this.A,{});b=this.A;g.tJ(b.g,a,c);b.requestId=a.get("req_id");Pwa(this,this.A);return}}b||null===this.F||(this.C?this.F(a.response,1E3*this.A.za[0].startTime):this.F(a.responseText,1E3*this.A.za[0].startTime));this.o=this.A=null};g.p(O5,K5);g.h=O5.prototype;g.h.ks=function(a,b){this.Fd();var c=Qwa(this,a.o);if(c){var d=1E3*c.index.Dn(c.index.wg()),e=g.W(this.C).ib;this.A=new N5(new g.cJ,this.C,c,function(c,e){b(c,a,e,d)},e,(0,g.z)(function(){e&&(this.A&&this.A.reset(),this.g&&this.g.reset(),this.D=!0)},this))}};
g.h.GB=function(){var a=this.D;this.D=!1;return a};
g.h.ls=function(a){g.W(this.C).ib?(H5(this.o,new g.vH({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),H5(this.o,new g.vH({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}))):H5(this.o,new g.vH({format:1,languageCode:"en",languageName:"English",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));a()};
g.h.Fd=function(){K5.prototype.Fd.call(this);this.A&&(this.A.dispose(),this.A=null)};
g.h.Lk=function(){return""};
g.h.V=function(){this.Fd();K5.prototype.V.call(this)};g.p(P5,f5);P5.prototype.Xp=function(a){var b=this.F.o;f5.prototype.Xp.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o==e)var d=f;else{d={};g.Ea(d,c.o);g.Ea(d,hxa);var e=c.o;var f=d}owa(this,c,d)}};
var hxa={qr:!0};g.p(Q5,f5);g.h=Q5.prototype;g.h.UB=function(){g.Pt(this.X)};
g.h.aR=function(){g.hq(this.element,"ytp-rollup-mode");this.Ji(this.la,!0)};
g.h.mx=function(){return this.I};
g.h.lx=function(){return this.F.params.Qo*R5(this)};
g.h.Ji=function(a,b){this.la=a;if(R5(this)){for(var c=0,d=0;d<this.A.length&&c<a.length;d++)this.A[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.A.concat(a.slice(c)));c=this.I;this.I=0;f5.prototype.Ji.call(this,a);this.I=Math.max(c,this.B.offsetWidth+1);c=this.F.params.Qo*R5(this)-this.B.offsetHeight;c!=this.O&&(b||(0,window.isNaN)(this.O)||(g.S(this.element,"ytp-rollup-mode"),g.Ot(this.X)),g.lh(this.B,"transform",c?"translateY("+c+"px)":""),this.O=c);f5.prototype.Ji.call(this,a)}else f5.prototype.Ji.call(this,
a)};g.p(S5,K5);g.h=S5.prototype;g.h.ks=function(a,b){var c=this.Lk(a),d=(0,g.z)(function(c){this.A=null;b(c.responseText,a)},this);
this.Fd();this.A=g.TD(c,{format:"RAW",Jb:d,withCredentials:!0})};
g.h.ls=function(a,b,c){var d=this.C;b={type:"list",tlangs:1,v:this.B,fmts:Number(b||!1),vssids:1};this.uy&&(b.asrs=1);d=g.MD(d,b);b=(0,g.z)(function(b){this.A=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.o,e=g.la(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("formats");var n=m.getAttribute("lang_code"),q=m.getAttribute("lang_translated"),r=m.getAttribute("name"),v=m.getAttribute("kind"),B=m.getAttribute("id"),F="true"==m.getAttribute("cantran");
m=m.getAttribute("vss_id");H5(d,new g.vH({formats:l,format:c,languageCode:n,languageName:q,name:r,kind:v,id:B,is_servable:!0,is_translateable:F,vss_id:m}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),q=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),l={languageCode:l,languageName:n,languageOriginal:q,id:r},this.D[l.languageCode]=l.languageName,this.F.push(new g.uH(l))}a()},this);
this.Fd();this.A=g.TD(d,{format:"RAW",Jb:b,withCredentials:!0})};
g.h.Lk=function(a){var b=this.C,c={v:this.B,type:"track",lang:a.o,name:a.C,kind:a.B,fmt:a.A};a.g&&(c.tlang=$4(a));return b=g.MD(b,c)};
g.h.Fd=function(){K5.prototype.Fd.call(this);this.A&&this.A.abort()};
g.h.V=function(){this.Fd();K5.prototype.V.call(this)};g.p(V5,g.uU);g.h=V5.prototype;g.h.V=function(){if(this.G){var a=this.L.app.C;a&&iwa(a)}else Wwa(this,!1);g.uU.prototype.V.call(this)};
g.h.lz=function(){return this.G?!this.B.wa:this.B.captionTracks.length&&this.g.wh().Fk?!0:Rwa(this)};
g.h.load=function(a){g.uU.prototype.load.call(this);this.F=this.g.wh();if(this.C||a)this.o?(this.G&&!this.A.experiments.g("disable_native_caption_api")?Twa(this,!0):a?this.pB(a,this.o):3!=this.g.Ra()&&this.C.ks(this.o,(0,g.z)(this.pB,this)),this.g.ua("captionschanged",Z4(this.o))):this.g.ua("onCaptionsTrackListChanged");else{var b;a=this.B;a.wa||g.W(this.L).ib&&null!=a.oa&&null!=a.oa.g.rawcc?b=new O5(this.B.oa,this.g):this.B.captionTracks.length?b=new L5(this.B):b=new S5(this.B.Pm,this.B.videoId,
this.B.Wg||this.A.Wg||g.uN(this.B,"yt:cc_default_lang")||this.A.Oa,this.B.Om);this.C=b;b.ls((0,g.z)(this.CR,this),!0,this.G?"vtt":void 0,this.g.wh())}};
g.h.unload=function(){this.G?this.A.experiments.g("disable_native_caption_api")?iwa(this.L.app.C):this.o&&Twa(this,!1):(this.ea&&g.Qt(this.ea),g.kU(this.g,"captions"),this.N=[],this.C&&this.C.Fd(),this.J&&g.hU(this.g,this.J),this.nu());g.uU.prototype.unload.call(this);var a=g.ST(this.g.app);a&&a.D&&g.wO(a.D.A);this.g.ua("captionschanged",{})};
g.h.CR=function(){if(this.O||Rwa(this))var a=Swa(this,this.O);if(this.G){for(var b=G5(this.C.o,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.wH(e),srclang:$4(e),src:this.C.Lk(e),id:e.toString()};e==a&&(f["default"]=1);c.push(g.L("TRACK",f))}a=this.L.app.C;for(b=0;b<c.length;b++)a.g.appendChild(c[b]);(c=this.L.app.C.g)&&c.textTracks&&c.textTracks.addEventListener&&!this.A.experiments.g("disable_native_caption_api")&&this.X.P(c.textTracks,"change",this.DR)}else!this.o&&a&&W5(this,
a),this.g.ua("onCaptionsTrackListChanged"),this.g.ua("onApiChange")};
g.h.DR=function(){for(var a=this.L.app.C.g.textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=G5(this.C.o,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.o:null)!=b&&W5(this,b,!0)};
g.h.IT=function(){this.A.experiments.g("disable_native_caption_api")?this.loaded&&!this.G&&this.unload():!this.o&&this.G||this.unload()};
g.h.pB=function(a,b,c,d){if(a){this.C.GB()&&(this.N=[],g.kU(this.L,"captions"),this.da.Nk());a=Owa(this.C,a,b,c,d);g.hU(this.g,a);if(this.O&&(a={trackName:b.C,trackKind:b.B,trackLangCode:$4(b)},b.g&&(a.fromLangCode=b.o),g.bU(this.g,"cc",a),this.o!=(this.F&&this.F.Fk))){!this.O||g.yL(this.A)||g.NL(this.A)||(g.Qt(this.ea),b=e5({Tg:0,pi:5,Mi:5,Qo:2,textAlign:0,bk:0,lang:"en"}),this.aa=[b],a=g.U("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON"),this.ga||(c=new g.xU(g.lV()),g.N(this,c),this.ga=c.element),
c=b.end-b.start,(d=g.wH(this.o))&&this.aa.push(new b5(b.start,c,0,b.id,d)),this.aa.push(new b5(b.start,c,0,b.id,a[0]),new b5(b.start,c,0,b.id,this.ga,!0),new b5(b.start,c,0,b.id,a[1],!0)),g.hU(this.g,this.aa),g.Ot(this.ea));if(this.O||g.yL(this.A))Y5(this,"module-enabled",!0),this.F&&(this.F.g=this.o);(b=g.ST(this.g.app))&&b.D&&g.wO(b.D.A)}this.O=!1}};
g.h.QK=function(a){this.N.push(a);this.da.Nk()};
g.h.RK=function(a){g.Ta(this.N,a);!this.A.experiments.g("disable_remove_displayed_close_caption_cue")&&this.A.ib&&g.jU(this.g,[a]);this.da.Nk()};
g.h.wS=function(a){if(a instanceof c5){var b=this.W[a.id];b&&b.F!=a&&(b.dispose(),delete this.W[a.id],b=null);b||(b=Uwa(this,a))&&(this.W[a.id]=b)}else b=a.windowId,this.Z[b]||(this.Z[b]=[]),this.Z[b].push(a)};
g.h.NS=function(){Vwa(this,this.aa);this.aa=null};
g.h.YC=function(){this.da.stop();g.Xb(this.Z);this.N.sort(g.iP);var a=this.N;if(this.J){var b=(0,g.Gd)(a,function(a){return-1==this.J.indexOf(a)},this);
b.length&&(a=b)}(0,g.C)(a,this.wS,this);g.Kb(this.W,function(a,b){this.Z[b]?(a.element.parentNode||g.oU(this.g,a.element,4),a.Ji(this.Z[b])):(a.dispose(),delete this.W[b])},this)};
g.h.TB=function(){T5(this,{},!0)};
g.h.Qq=function(){var a=X5.sb;a={background:a.background,backgroundOpacity:a.Ye,charEdgeStyle:a.Th,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.cj,textOpacity:a.Gh,windowColor:X5.windowColor,windowOpacity:X5.nk};var b=U5(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.qu=function(a,b){var c={};g.Ea(c,U5(this,"display-settings"));g.Ea(c,a);T5(this,c,b);this.g.T("captionssettingschanged")};
g.h.nu=function(){!this.G&&this.loaded&&(g.Kb(this.W,function(a,b){a.dispose();delete this.W[b]},this),this.YC())};
g.h.Ds=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.Yc(b,-2,4);this.qu({fontSizeIncrement:c});return c;case "reload":b&&!this.G&&W5(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.A.Gb&&Y5(this,"module-enabled",!!b);break;case "track":if(!this.C)return{};if(b){if(this.G)break;if(!g.Aa(b))break;if(g.Wb(b)){W5(this,null,!0);break}for(var d=G5(this.C.o,!0),e=0;e<d.length;e++){var f=d[e];f.o!=b.languageCode||c&&f.D!=b.languageName||(c=b.translationLanguage?hwa(f,
b.translationLanguage):f)}!c||c==this.o&&this.loaded||W5(this,c,!0)}else return this.loaded&&this.o&&this.o!=(this.F&&this.F.Fk)?Z4(this.o):{};return"";case "tracklist":return this.C?(0,g.J)(G5(this.C.o,b&&b.includeAsr),function(a){return Z4(a)}):[];
case "translationLanguages":return this.C?this.C.F:[];case "displaySettings":c=this.Qq();if(g.yL(this.A)&&b&&g.Aa(b))if(b.reset)this.TB();else{f={};for(d in b)switch(d){case "color":case "background":case "windowColor":f[d]=Xwa(b[d],c[d]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[d]=Ywa(b[d],c[d]);break;case "charEdgeStyle":f[d]=$wa(b[d],c[d]);break;case "fontSizeIncrement":f[d]=cxa(b[d],c[d]);break;case "fontFamilyOption":f.fontFamily=bxa(b[d],c[d])}for(e in f)f[e+
"Override"]=!0;this.qu(f,!0);c=this.Qq()}c.fontFamilyOption=axa[c.fontFamily];c.charEdgeStyle=Zwa[c.charEdgeStyle];return c;case "sampleSubtitles":this.G||void 0==b||Wwa(this,!!b);break;case "xmlTrack":b&&this.A.Gb&&(this.G||W5(this,new g.vH({languageName:b.name}),!1,b.xml))}};
g.h.OK=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.A.Gb&&a.push("stickyLoading","xmlTrack");return a};
g.h.PK=function(){var a=this.o;return a?{cc:a.F}:{}};
g.h.KC=function(){this.loaded&&this.o?(Y5(this,"module-enabled",!1),this.unload()):W5(this,this.o||Swa(this,!0),!0)};
g.h.bO=function(){this.B.captionTracks.length&&(this.loaded&&this.unload(),this.lz()&&this.load())};g.CY.captions=V5;})(_yt_player);
